name: Remove contributor
description: Request removing a contributor.
title: "Remove [Contributor]"
labels: ["contributor:remove"]
body:
 - type: input
   id: github-username
   attributes:
     label: GitHub username
     description: Enter the username of the contributor to remove, without @.
     placeholder: octocat
   validations:
     required: true
